<!-- Menu Centro -->
<div class="menu-centro">
    <ul>
        <li>
            <a class="flat-button" href="<?php echo $this->url('modulos'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Administrativo: Visualize, registre e edite todos os módulos e suas funções disponíveis no sistema."> <span class="glyphicon" data-icon="&#xe0a5;"></span>
                <div class="flat-button-label"> Módulos & Ações </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('grupos'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Grupos de Usuários"> <span class="glyphicon" data-icon="&#xe0a5;"></span>
                <div class="flat-button-label"> Grupos de Usuários </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('usuarios'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Usuários do Sistema"> <span class="glyphicon" data-icon="&#xe1e0;"></span>
                <div class="flat-button-label"> Usuários </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('prioridades'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Visualizar dados de projetos prioritários"> <span class="glyphicon" data-icon="&#xe177;"></span>
                <div class="flat-button-label"> Projetos Prioritários </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('relatorios'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Gerar Relatórios de Meta física Realizadas"> <span class="glyphicon" data-icon="&#xe17e;"></span>
                <div class="flat-button-label"> Consultar e Gerar Relatórios </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('metafisicas'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Consulte, Adicione, Edite ou Remova meta física realizadas"> <span class="glyphicon" data-icon="^"></span>
                <div class="flat-button-label"> Metas físicas Realizadas </div>
            </a>
        </li>
        <li>
            <a class="flat-button" href="<?php echo $this->url('execorcs'); ?>" data-toggle="tooltip" data-placement="top" data-original-title="Consulte, Adicione, Edite ou Remova dados referentes"> <span class="glyphicon" data-icon="&#xe144;"></span>
                <div class="flat-button-label"> Execuções Orçamentárias </div>
            </a>
        </li>
    </ul>
</div>