<?php
$title = 'Excluir Meta Física';
$this->headTitle($title);
?>
<div class="container-fluid">
    <div class="table-responsive">
        <h1><?php echo $this->escapeHtml($title); ?></h1>

        <table class="table table-striped" id="datatable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Projeto - Descrição</th>
                    <th>Orç.Previsto</th>
                    <th>Orç.Planejado(/mês)</th>
                    <th>Orç.Realizado(/mês)</th>
                    <th>Meta física Prevista(/mês)</th>
                    <th>Meta física Realizada(/mês)</th>
                    <th>Período</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?php echo $this->escapeHtml($meta->m_codigo); ?></td>
                    <td><?php echo $this->escapeHtml($meta->m_projeto); ?> - <?php echo $this->escapeHtml($meta->p_desc); ?></td>
                    <td>R$<?php echo number_format($this->escapeHtml($meta->e_execprev), 2, ',', '.'); ?></td>
                    <td>R$<?php echo number_format($this->escapeHtml($meta->m_execorcplan), 2, ',', '.'); ?></td>
                    <td>R$<?php echo number_format($this->escapeHtml($meta->m_execorcreal), 2, ',', '.'); ?></td>
                    <td style="text-align: center;"><?php echo $this->escapeHtml($meta->p_meta); ?></td>
                    <td style="text-align: center;"><?php echo $this->escapeHtml($meta->m_metarealizada); ?></td>
                    <td><?php echo $this->escapeHtml($meta->m_periodo); ?></td>
                </tr>
            </tbody>
        </table>
        <div class="col-md-12 text-center">
            <h2 class="sub-header" style="margin-bottom: 20px;">Confirma Exclusão?</h2>
        </div>
        <div class="col-md-12 text-center">
            <?php $url = $this->url('metafisicas', array('action' => 'deletemeta', 'form_codigo' => $this->form_codigo)); ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="hidden" name="id" value="<?php echo (int) $meta->form_codigo; ?>" />
                    <input type="submit" name="del" class="btn btn-primary" value="Confirmar" />
                    <input type="submit" name="del" class="btn btn-danger" value="Cancelar" />
                </div>
            </form>
        </div>
    </div>
</div>
